# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# ======================================================================
# === about ============================================================
# ======================================================================
[[main]]
  name = "About Us"
  url = "#about"
  weight = 10

[[main]]
  name = "Description"
  weight = 10
  parent = "About Us"
  url = "about/description"

[[main]]
  name = "Mission"
  weight = 20
  parent = "About Us"
  url = "about/mission"

[[main]]
  name = "Vision"
  weight = 30
  parent = "About Us"
  url = "about/vision"

[[main]]
  name = "Guiding Principles"
  weight = 40
  parent = "About Us"
  url = "about/guiding_principles"

[[main]]
  name = "Ethics and Values"
  weight = 50
  parent = "About Us"
  url = "about/ethics_and_values"

[[main]]
  name = "Timeline"
  weight = 60
  parent = "About Us"
  url = "about/timeline"

[[main]]
  name = "People"
  weight = 70
  parent = "About Us"
  url = "about/people"

[[main]]
  name = "Strategy and Implementation"
  weight = 80
  parent = "About Us"
  url = "about/strategy_and_implementation"
  
  
# ======================================================================
# === /about ===========================================================
# ======================================================================

[[main]]
  name = "The Network"
  url = "#network"
  weight = 20

[[main]]
  name = "Products"
  url = "#products"
  weight = 30

[[main]]
  name = "Join MBON"
  url = "#projects"
  weight = 40
# ======================================================================
# === /news and events ===========================================================
# ======================================================================
[[main]]
  name = "News and Events"
  url = "#news_events"
  weight = 50
  
 [[main]]
  name = "News"
  weight = 10
  parent = "News and Events"
  url = "news_events/news"
 
  [[main]]
  name = "Events"
  weight = 20
  parent = "News and Events"
  url = "news_events/events"


# ======================================================================
# === /news and events ===========================================================
# ======================================================================

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 60

[[main]]
  name = "Contacts"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
